server:
  port: 8090

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

spring:
  cloud:
    gateway:
      routes:
        - id: api-route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

dubbo:
  application:
    name: hygod-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848